package com.ddl.dao;

import com.ddl.model.TorderItem;
import com.ddl.model.TorderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TorderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbggenerated Tue Jul 19 18:03:20 CST 2016
     */
    int countByExample(TorderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbggenerated Tue Jul 19 18:03:20 CST 2016
     */
    int deleteByExample(TorderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbggenerated Tue Jul 19 18:03:20 CST 2016
     */
    int deleteByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbggenerated Tue Jul 19 18:03:20 CST 2016
     */
    int insert(TorderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbggenerated Tue Jul 19 18:03:20 CST 2016
     */
    int insertSelective(TorderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbggenerated Tue Jul 19 18:03:20 CST 2016
     */
    List<TorderItem> selectByExample(TorderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbggenerated Tue Jul 19 18:03:20 CST 2016
     */
    TorderItem selectByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbggenerated Tue Jul 19 18:03:20 CST 2016
     */
    int updateByExampleSelective(@Param("record") TorderItem record, @Param("example") TorderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbggenerated Tue Jul 19 18:03:20 CST 2016
     */
    int updateByExample(@Param("record") TorderItem record, @Param("example") TorderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbggenerated Tue Jul 19 18:03:20 CST 2016
     */
    int updateByPrimaryKeySelective(TorderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbggenerated Tue Jul 19 18:03:20 CST 2016
     */
    int updateByPrimaryKey(TorderItem record);
}